### ISSUE TITLE
Linking CSS to HTML templates

### ISSUE THREAD

**Issue by JOHNMULAMA** [Calvince-Okoth/WMS#1]
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

use the above in  sign HTML to load CSS

**Comment by JOHNMULAMA** [comment]
<link rel="stylesheet" type="text/css" href="{% static 'sstyles.css' %}">  should fix

**Comment by Calvince-Okoth** [comment]
nice currntly working. thank you
